title: Andrew Chin
logo: /assets/images/profile.jpg
description: >
  Ph.D. Student<br>
  School of Cybersecurity and Privacy<br>
  Georgia Institute of Technology<br>
  CODA S0971Y, Atlanta GA<br>
  <a href="mailto:achin34@gatech.edu">achin34@gatech.edu</a><br>
  <a href="https://github.com/azchin">[Github]</a> <a href="https://www.linkedin.com/in/andrew-chin-97749516a">[LinkedIn]</a> 
github: [metadata]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
